### ISSUE TITLE
node 2 worker crashing - baseconsumer getting 4 args instead of 3.

### ISSUE THREAD

**Issue by glenndavy** [pgq/skytools-legacy#24]
Hi there,

I've pasted the trace back below, but basically the worker on the clone continually dumping this error:

2013-01-24 12:01:31,047 20806 INFO {idle: 301.2509}
2013-01-24 12:01:31,059 20806 ERROR Job 83_92_sa_replication_clone crashed: **init**() takes exactly 3 arguments (4 given)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/skytools/scripting.py", line 567, in run_func_safely
    return func()
  File "/usr/local/lib/python2.7/dist-packages/pgq/cascade/consumer.py", line 199, in work
    return BaseConsumer.work(self)
  File "/usr/local/lib/python2.7/dist-packages/pgq/baseconsumer.py", line 256, in work
    self._launch_process_batch(db, batch_id, ev_list)
  File "/usr/local/lib/python2.7/dist-packages/pgq/baseconsumer.py", line 285, in _launch_process_batch
    self.process_batch(db, batch_id, list)
  File "/usr/local/lib/python2.7/dist-packages/pgq/cascade/consumer.py", line 172, in process_batch
    self.process_remote_batch(src_db, tick_id, event_list, dst_db)
  File "/usr/local/lib/python2.7/dist-packages/londiste/playback.py", line 375, in process_remote_batch
    CascadedWorker.process_remote_batch(self, src_db, tick_id, ev_list, dst_db)
  File "/usr/local/lib/python2.7/dist-packages/pgq/cascade/worker.py", line 149, in process_remote_batch
    for ev in event_list:
  File "/usr/local/lib/python2.7/dist-packages/pgq/baseconsumer.py", line 56, in __iter__
    ev = self._event_class(self, self.queue_name, row)
TypeError: __init__() takes exactly 3 arguments (4 given)

**Comment by glenndavy** [comment]
closing this... pulling latest code and re-doing configure&&make&&make install fixed it
